/**
 * =============================================================================
 * DATABASE MODULE - SQLite + sqlite-vec for vector storage
 * =============================================================================
 * 
 * This module handles all database operations for storing and retrieving
 * code chunks with their vector embeddings.
 * 
 * WHY DO WE NEED A DATABASE?
 * --------------------------
 * 1. We need to store code chunks somewhere so we can search them later
 * 2. We need to store vector embeddings (arrays of 384 numbers) for each chunk
 * 3. We need to find similar chunks quickly when user searches
 * 
 * WHY SQLITE + sqlite-vec?
 * -----------------------
 * - SQLite: Simple file-based database, no server needed
 * - sqlite-vec: Extension that lets us do fast vector similarity search
 *   (finds chunks that are "similar" to a query using math)
 * 
 * WHAT IS VECTOR SEARCH?
 * ----------------------
 * - Regular search: finds exact matches ("function add")
 * - Vector search: finds semantically similar code
 * - Example: searching "calculate total" might find "sumValues()"
 * - This is the "R" in RAG (Retrieval-Augmented Generation)
 * 
 * =============================================================================
 */

import Database from 'better-sqlite3';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { getSqliteVecExtensionPath, getPlatformInfo } from './platform.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * =============================================================================
 * INTERFACES - Defining the shape of our data
 * =============================================================================
 * 
 * Think of interfaces as a blueprint or contract. They tell TypeScript
 * what fields our data objects should have.
 */

// This is what a single code chunk looks like in our system
// We use "?" to mark optional fields (like id, which is auto-generated)
export interface CodeChunk {
  id?: number;                    // Auto-generated by SQLite
  file_path: string;              // Where the code lives (e.g., "/src/main.ts")
  file_hash: string;              // MD5 hash of entire file content
  chunk_text: string;             // The actual code text
  start_line: number;             // Which line does this chunk start at?
  end_line: number;               // Which line does this chunk end at?
  content_hash: string;           // MD5 hash of chunk content (for dedup)
  embedding?: number[];           // 384-dimensional vector (optional for search)
  created_at?: string;            // When was this stored?
  updated_at?: string;            // When was it last updated?
}

// This is what a search result looks like
export interface SearchResult {
  id: number;
  file_path: string;
  chunk_text: string;
  start_line: number;
  end_line: number;
  // Similarity is a number between 0 and 1
  // 1 = exact match, 0 = no similarity
  similarity: number;
}

/**
 * =============================================================================
 * CODE DATABASE CLASS - The main class that handles all DB operations
 * =============================================================================
 * 
 * This class manages:
 * 1. Connection to SQLite database
 * 2. Creating/updating code chunks
 * 3. Vector similarity search
 * 4. Statistics and cleanup
 */

export class CodeDatabase {
  // The actual SQLite database connection (null until connected)
  private db: Database.Database | null = null;
  
  // Where to store the database file
  private dbPath: string;

  /**
   * =============================================================================
   * CONSTRUCTOR - Set up database location
   * =============================================================================
   * 
   * @param dbPath - Optional custom path to the SQLite file
   * 
   * PRIORITY ORDER:
   * 1. Provided dbPath parameter
   * 2. DB_PATH environment variable
   * 3. "codeindexer.db" in current working directory
   * 
   * EXAMPLE:
   * new CodeDatabase()                    → ./codeindexer.db
   * new CodeDatabase('/tmp/my.db')        → /tmp/my.db
   * DB_PATH=/custom/path DB codeindexer   → /custom/path
   */
  constructor(dbPath?: string) {
    // Use provided path, or check environment, or default to current folder
    this.dbPath = dbPath || process.env.DB_PATH || path.join(process.cwd(), 'codeindexer.db');
  }

  /**
   * =============================================================================
   * CONNECT - Initialize the database connection
   * =============================================================================
   * 
   * This must be called BEFORE any other database operations!
   * 
   * WHAT IT DOES:
   * 1. Creates/opens the SQLite database file
   * 2. Enables WAL mode (Write-Ahead Logging) - better performance
   * 3. Loads sqlite-vec extension for vector search
   * 4. Creates the database tables if they don't exist
   * 
   * WHY WAL MODE?
   * - SQLite normally locks the entire database when writing
   * - WAL (Write-Ahead Logging) allows concurrent reads while writing
   * - Makes our indexer faster!
   * 
   * WHAT IS sqlite-vec?
   * - Extension that adds vector operations to SQLite
   * - Lets us do fast cosine similarity search
   * - Without it, we'd have to load all vectors into memory
   */
  async connect(): Promise<void> {
    // Already connected? Skip.
    if (this.db) {
      return;
    }

    try {
      // Log platform information for debugging
      const platformInfo = getPlatformInfo();
      console.log(`[Database] Platform: ${platformInfo.platform} (${platformInfo.os} ${platformInfo.arch})`);
      
      // Step 1: Open/create the database file
      this.db = new Database(this.dbPath);
      
      // Step 2: Enable WAL mode for better performance
      // WAL = Write-Ahead Logging - allows concurrent reads
      this.db.pragma('journal_mode = WAL');

      // Step 3: Load vector search extension (sqlite-vec)
      // This enables fast cosine similarity search on embeddings
      // Automatically detects platform and loads correct extension
      const extensionPath = getSqliteVecExtensionPath();
      console.log('[Database] Loading sqlite-vec from:', extensionPath);
      this.db.loadExtension(extensionPath);
      
      // Verify the extension loaded by getting its version
      const version = this.db.prepare("SELECT vec_version() as v").get() as { v: string };
      console.log('[Database] sqlite-vec loaded:', version.v);

      // Step 4: Create tables if they don't exist
      this.initializeSchema();
      
      console.log('[Database] Connected to:', this.dbPath);
    } catch (error) {
      console.error('[Database] Failed to connect:', error);
      throw error;
    }
  }

  /**
   * =============================================================================
   * INITIALIZE SCHEMA - Create tables and indexes
   * =============================================================================
   * 
   * This creates the structure of our database:
   * 
   * TABLE: code_chunks
   * -----------------
   * - id: Unique number for each chunk (auto-increment)
   * - file_path: Which file this chunk came from
   * - file_hash: MD5 hash of entire file (for incremental indexing)
   * - chunk_text: The actual code
   * - start_line / end_line: Where in the file
   * - content_hash: MD5 hash of chunk (for deduplication)
   * - embedding: The 384-number vector (stored as BLOB binary)
   * - created_at / updated_at: Timestamps
   * 
   * UNIQUE CONSTRAINT:
   * - file_path + content_hash must be unique together
   * - This prevents duplicates if file hasn't changed
   * 
   * INDEXES:
   * - idx_file_path: Speed up finding chunks by file
   * - idx_file_hash: Speed up hash lookups
   * 
   * VIRTUAL TABLE: code_chunks_vec
   * ------------------------------
   * - This is created by sqlite-vec
   * - Enables fast vector similarity search
   * - Stores embeddings optimized for cosine distance
   */
  private initializeSchema(): void {
    // Can't initialize without a connection
    if (!this.db) throw new Error('Database not connected');

    // Create the main chunks table
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS code_chunks (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_path TEXT NOT NULL,
        file_hash TEXT NOT NULL,
        chunk_text TEXT NOT NULL,
        start_line INTEGER NOT NULL,
        end_line INTEGER NOT NULL,
        content_hash TEXT NOT NULL,
        embedding BLOB,
        created_at TEXT DEFAULT (datetime('now')),
        updated_at TEXT DEFAULT (datetime('now')),
        UNIQUE(file_path, content_hash)
      )
    `);

    // Create index on file_path for faster lookups
    this.db.exec(`CREATE INDEX IF NOT EXISTS idx_file_path ON code_chunks(file_path)`);
    
    // Create index on file_hash for change detection
    this.db.exec(`CREATE INDEX IF NOT EXISTS idx_file_hash ON code_chunks(file_hash)`);

    // Create virtual table for vector search (sqlite-vec)
    // This enables fast cosine similarity search!
    this.db.exec(`
      CREATE VIRTUAL TABLE IF NOT EXISTS code_chunks_vec USING vec0(
        chunk_id TEXT,
        embedding float[384]
      )
    `);
  }

  /**
   * =============================================================================
   * GET FILE HASH - Retrieve stored hash for a file
   * =============================================================================
   * 
   * Used for incremental indexing: check if a file has changed
   * 
   * @param filePath - Path to the source file
   * @returns The MD5 hash stored in DB, or null if not found
   * 
   * WHAT IT'S USED FOR:
   * - Before re-indexing, we check if the file changed
   * - If hash is same, skip re-indexing (save time!)
   * - If hash is different, re-index the file
   * 
   * EXAMPLE:
   * getFileHash("/src/main.ts")
   * Returns: "5d41402abc4b2a76b9719d911017c592"
   * Or null if file was never indexed
   */
  getFileHash(filePath: string): string | null {
    if (!this.db) throw new Error('Database not connected');

    try {
      // Prepare a parameterized query (prevents SQL injection)
      const stmt = this.db.prepare('SELECT file_hash FROM code_chunks WHERE file_path = ? LIMIT 1');
      const row = stmt.get(filePath) as { file_hash: string } | undefined;
      return row?.file_hash || null;  // Return hash or null if not found
    } catch (error) {
      console.error('[Database] Error getting file hash:', error);
      return null;
    }
  }

  /**
   * =============================================================================
   * GET ALL FILE HASHES - Get all stored file hashes at once
   * =============================================================================
   * 
   * This is used for incremental re-indexing. Instead of checking
   * each file one by one, we load all hashes at startup.
   * 
   * @returns Map of file path → file hash
   * 
   * WHY MAP?
   * - O(1) lookup time instead of O(n) database queries
   * - Much faster when checking thousands of files
   * 
   * EXAMPLE:
   * getAllFileHashes()
   * Returns: Map {"/src/main.ts" → "abc123", "/src/utils.ts" → "def456"}
   */
  getAllFileHashes(): Map<string, string> {
    if (!this.db) throw new Error('Database not connected');

    try {
      // Get all unique file paths and their hashes
      const stmt = this.db.prepare('SELECT DISTINCT file_path, file_hash FROM code_chunks');
      const rows = stmt.all() as Array<{ file_path: string; file_hash: string }>;
      
      // Convert to Map for fast lookups
      const hashMap = new Map<string, string>();
      for (const row of rows) {
        hashMap.set(row.file_path, row.file_hash);
      }
      return hashMap;
    } catch (error) {
      console.error('[Database] Error getting file hashes:', error);
      return new Map();
    }
  }

  /**
   * =============================================================================
   * INSERT CHUNK - Store a code chunk in the database
   * =============================================================================
   * 
   * This is how we save a parsed code chunk to the database.
   * 
   * @param chunk - The CodeChunk object with all details
   * @returns The ID of the inserted chunk, or null if failed
   * 
   * WHAT THE QUERY DOES:
   * 1. INSERT: Try to insert new row
   * 2. ON CONFLICT: If file_path + content_hash already exists
   * 3. DO UPDATE: Just update the embedding and timestamp
   * 
   * WHY THIS PATTERN?
   * - Prevents duplicate chunks for unchanged files
   * - Updates embeddings if they changed
   * - Single query does both insert and update!
   * 
   * EMBEDDING STORAGE:
   * - Convert number[] to Float32Array for efficient storage
   * - Then to Buffer (binary) for SQLite BLOB storage
   * - This uses less space than storing JSON strings
   */
  insertChunk(chunk: CodeChunk): number | null {
    if (!this.db) throw new Error('Database not connected');

    try {
      // Convert embedding array to binary blob for storage
      let embeddingBlob: Buffer | null = null;
      if (chunk.embedding) {
        const float32 = new Float32Array(chunk.embedding);
        embeddingBlob = Buffer.from(float32.buffer);
      }

      // Prepare the insert/update query
      // ON CONFLICT handles the case where this exact chunk already exists
      const stmt = this.db.prepare(`
        INSERT INTO code_chunks (file_path, file_hash, chunk_text, start_line, end_line, content_hash, embedding)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(file_path, content_hash) 
        DO UPDATE SET
          file_hash = excluded.file_hash,
          chunk_text = excluded.chunk_text,
          start_line = excluded.start_line,
          end_line = excluded.end_line,
          embedding = excluded.embedding,
          updated_at = datetime('now')
      `);

      // Execute with all the chunk data
      const result = stmt.run(
        chunk.file_path,
        chunk.file_hash,
        chunk.chunk_text,
        chunk.start_line,
        chunk.end_line,
        chunk.content_hash,
        embeddingBlob
      );

      const lastId = result.lastInsertRowid as number;

      // If we have an embedding, also insert into the vec table
      // This enables fast similarity search!
      if (chunk.embedding && lastId) {
        this.upsertVector(lastId, chunk.embedding);
      }

      return lastId;
    } catch (error) {
      console.error('[Database] Error inserting chunk:', error);
      return null;
    }
  }

  /**
   * =============================================================================
   * INSERT CHUNKS BATCH - Insert multiple chunks in one transaction
   * =============================================================================
   * 
   * Much faster than inserting one at a time!
   * 
   * @param chunks - Array of CodeChunk objects
   * @returns Number of chunks successfully inserted
   * 
   * WHY TRANSACTIONS?
   * - By default, each INSERT is its own transaction
   * - This means disk sync for EACH insert (slow!)
   * - Batching wraps many inserts in ONE transaction
   * - Result: 10-100x faster for bulk inserts!
   * 
   * EXAMPLE:
   * insertChunksBatch([chunk1, chunk2, chunk3])
   * Returns: 3 (all three inserted successfully)
   */
  insertChunksBatch(chunks: CodeChunk[]): number {
    if (!this.db) throw new Error('Database not connected');

    // Prepare statements once (more efficient than preparing each time)
      const insertChunk = this.db.prepare(`
        INSERT INTO code_chunks (file_path, file_hash, chunk_text, start_line, end_line, content_hash, embedding)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(file_path, content_hash) 
        DO UPDATE SET
          file_hash = excluded.file_hash,
          chunk_text = excluded.chunk_text,
          start_line = excluded.start_line,
          end_line = excluded.end_line,
          embedding = excluded.embedding,
          updated_at =datetime('now')
        RETURNING id
      `);

      const insertVector = this.db.prepare(`
        INSERT INTO code_chunks_vec(chunk_id, embedding) VALUES (?, ?)
      `);

      let insertedCount = 0;

      // Wrap all inserts in a single transaction
      const insertTransaction = this.db.transaction(() => {
        for (const chunk of chunks) {
          try {
            // Convert embedding to blob
            let embeddingBlob: Buffer | null = null;
            if (chunk.embedding) {
              const float32 = new Float32Array(chunk.embedding);
              embeddingBlob = Buffer.from(float32.buffer);
            }

            // Insert the chunk
            const result = insertChunk.run(
              chunk.file_path,
              chunk.file_hash,
              chunk.chunk_text,
              chunk.start_line,
              chunk.end_line,
              chunk.content_hash,
              embeddingBlob
            );

            const lastId = result.lastInsertRowid as number;

            // Also insert/update the vector for similarity search
            if (chunk.embedding && lastId) {
              // Delete old vector first (upsert behavior)
              this.db!.prepare("DELETE FROM code_chunks_vec WHERE chunk_id = ?").run(String(lastId));
              insertVector.run(String(lastId), embeddingBlob);
            }

            insertedCount++;
          } catch (error) {
            // Log but continue with other chunks
            console.error('[Database] Error in batch insert for chunk:', error);
          }
        }
      });

      // Execute the entire transaction
      insertTransaction();
      return insertedCount;
  }

  /**
   * =============================================================================
   * UPSERT VECTOR - Update or insert vector in search table
   * =============================================================================
   * 
   * Handles the vector storage for similarity search.
   * Deletes old vector first, then inserts new one.
   * 
   * @param chunkId - The chunk ID (links to main table)
   * @param embedding - The 384-dimensional vector
   * 
   * WHY DELETE FIRST?
   * - sqlite-vec doesn't have native "upsert"
   * - We need to remove old vector before inserting new one
   * - This keeps vectors in sync with main table
   */
  private upsertVector(chunkId: number, embedding: number[]): void {
    if (!this.db) return;

    try {
      // Delete any existing vector for this chunk
      this.db.prepare("DELETE FROM code_chunks_vec WHERE chunk_id = ?").run(String(chunkId));

      // Convert embedding to binary blob
      const float32 = new Float32Array(embedding);
      const buffer = Buffer.from(float32.buffer);

      // Insert the new vector
      this.db.prepare('INSERT INTO code_chunks_vec(chunk_id, embedding) VALUES (?, ?)').run(String(chunkId), buffer);
    } catch (error) {
      console.error(`[Database] Error upserting vector for chunk ${chunkId}:`, error);
    }
  }

  /**
   * =============================================================================
   * DELETE CHUNKS BY FILE - Remove all chunks from a file
   * =============================================================================
   * 
   * Used when a file is deleted or we want to re-index from scratch
   * 
   * @param filePath - Path to the file to remove
   * @returns True if successful
   * 
   * WHY DELETE FROM BOTH TABLES?
   * - code_chunks is the main data table
   * - code_chunks_vec is the vector search table
   * - Must delete from both to keep things in sync!
   * 
   * EXAMPLE:
   * deleteChunksByFile("/src/deleted.ts")
   * Returns: true
   */
  deleteChunksByFile(filePath: string): boolean {
    if (!this.db) throw new Error('Database not connected');

    try {
      // First, get all chunk IDs for this file
      const ids = this.db.prepare('SELECT id FROM code_chunks WHERE file_path = ?').all(filePath) as { id: number }[];
      
      // Delete from vector table first
      for (const row of ids) {
        this.db.prepare('DELETE FROM code_chunks_vec WHERE chunk_id = ?').run(String(row.id));
      }

      // Then delete from main table
      this.db.prepare('DELETE FROM code_chunks WHERE file_path = ?').run(filePath);
      return true;
    } catch (error) {
      console.error('[Database] Error deleting chunks:', error);
      return false;
    }
  }

  /**
   * =============================================================================
   * GET ALL CHUNKS - Retrieve all stored chunks
   * =============================================================================
   * 
   * Used for getting statistics about the index
   * 
   * @returns Array of all CodeChunk objects
   * 
   * WARNING: Don't call this on large codebases!
   * Use getStats() for summary information instead.
   */
  getAllChunks(): CodeChunk[] {
    if (!this.db) throw new Error('Database not connected');

    try {
      const stmt = this.db.prepare('SELECT id, file_path, file_hash, chunk_text, start_line, end_line, content_hash, created_at, updated_at FROM code_chunks');
      return stmt.all() as CodeChunk[];
    } catch (error) {
      console.error('[Database] Error getting all chunks:', error);
      return [];
    }
  }

  /**
   * =============================================================================
   * GET STATISTICS - Get summary info about indexed data
   * =============================================================================
   * 
   * Returns counts of chunks and files in the database.
   * 
   * @returns Object with totalChunks and totalFiles
   * 
   * WHY TWO COUNTS?
   * - One file can have many chunks (functions, classes, etc.)
   * - totalChunks: how many code pieces we've stored
   * - totalFiles: how many unique files
   * 
   * EXAMPLE:
   * getStats()
   * Returns: { totalChunks: 150, totalFiles: 12 }
   */
  getStats(): { totalChunks: number; totalFiles: number } {
    if (!this.db) throw new Error('Database not connected');

    try {
      // Count all chunks
      const chunks = this.db.prepare('SELECT COUNT(*) as count FROM code_chunks').get() as { count: number };
      // Count unique files
      const files = this.db.prepare('SELECT COUNT(DISTINCT file_path) as count FROM code_chunks').get() as { count: number };
      
      return {
        totalChunks: chunks.count,
        totalFiles: files.count,
      };
    } catch (error) {
      console.error('[Database] Error getting stats:', error);
      return { totalChunks: 0, totalFiles: 0 };
    }
  }

  /**
   * =============================================================================
   * SEARCH SIMILAR - Find chunks similar to query embedding
   * =============================================================================
   * 
   * THIS IS THE CORE OF THE RAG SYSTEM!
   * 
   * Takes a query embedding (from natural language) and finds
   * the most similar code chunks using vector math.
   * 
   * @param queryEmbedding - The 384-dim vector from the search query
   * @param limit - How many results to return (default: 5)
   * @returns Array of SearchResult sorted by similarity
   * 
   * HOW VECTOR SEARCH WORKS:
   * 1. Convert query to embedding using Transformers.js
   * 2. Compare against all stored embeddings using cosine distance
   * 3. Sort by distance (closest = most similar)
   * 4. Return top matches
   * 
   * WHAT IS COSINE DISTANCE?
   * - Measures how different two vectors are
   * - 0 = identical (most similar)
   * - 2 = opposite (no similarity)
   * - We convert to similarity: similarity = 1 - distance
   * 
   * EXAMPLE:
   * searchSimilar([0.1, -0.3, 0.5, ...], 3)
   * Returns: [
   *   { id: 5, file_path: "src/utils.ts", similarity: 0.92, ... },
   *   { id: 12, file_path: "src/helpers.ts", similarity: 0.87, ... },
   *   { id: 3, file_path: "src/lib.ts", similarity: 0.81, ... }
   * ]
   */
  async searchSimilar(queryEmbedding: number[], limit: number = 5): Promise<SearchResult[]> {
    if (!this.db) throw new Error('Database not connected');

    // Convert embedding to binary blob for the query
    const float32 = new Float32Array(queryEmbedding);
    const buffer = Buffer.from(float32.buffer);

    // Use sqlite-vec's cosine distance function
    // This is MUCH faster than loading all vectors into JavaScript
    const stmt = this.db.prepare(`
      SELECT 
        v.chunk_id,
        vec_distance_cosine(v.embedding, ?) as distance,
        c.file_path,
        c.chunk_text,
        c.start_line,
        c.end_line
      FROM code_chunks_vec v
      JOIN code_chunks c ON c.id = CAST(v.chunk_id AS INTEGER)
      ORDER BY distance
      LIMIT ?
    `);

    const results = stmt.all(buffer, limit) as Array<{
      chunk_id: string;
      distance: number;
      file_path: string;
      chunk_text: string;
      start_line: number;
      end_line: number;
    }>;

    // Convert distance to similarity (1 - distance)
    // Lower distance = higher similarity
    return results.map(row => ({
      id: parseInt(row.chunk_id, 10),
      file_path: row.file_path,
      chunk_text: row.chunk_text,
      start_line: row.start_line,
      end_line: row.end_line,
      similarity: 1 - row.distance,
    }));
  }

  /**
   * =============================================================================
   * CLOSE - Clean up database connection
   * =============================================================================
   * 
   * Always call this when done using the database!
   * Closes the connection and releases resources.
   * 
   * WHY CLOSE?
   * - Releases file locks
   * - Flushes any pending writes
   * - Allows other processes to access the database
   * 
   * EXAMPLE:
   * await indexer.close();
   * // Database connection now closed
   */
  close(): void {
    if (this.db) {
      this.db.close();
      this.db = null;
    }
  }
}

// Create a single shared instance that we'll use throughout the app
// This follows the "Singleton" pattern - only one database connection
export const db = new CodeDatabase();
